version: "2"
services:
  app:
    image: rishabh050189/springcrud:14
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springbootdb
    volumes:
      - ./mounts/db_data:/var/lib/mysql/data

